services:
  ollama-proxy:
    build: .
    restart: unless-stopped
    image: ollama-proxy
    ports:
      - "11434:11434"
    env_file:
      - .env
    container_name: ollama-proxy
    environment:
      - OPENAI_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_HTTP_REFERER=${OPENROUTER_HTTP_REFERER}
      - OPENROUTER_X_TITLE=${OPENROUTER_X_TITLE}